import React, { useState } from 'react';
import { InputSection } from './components/InputSection';
import { ReviewDisplay } from './components/ReviewDisplay';
import { AboutModal } from './components/AboutModal';
import { analyzeSubstackPost, analyzeRawText } from './services/geminiService';
import { AnalysisStatus, AnalysisError, ReviewResponse } from './types';
import { BookOpen, AlertCircle } from 'lucide-react';

const App: React.FC = () => {
  const [status, setStatus] = useState<AnalysisStatus>(AnalysisStatus.IDLE);
  const [data, setData] = useState<ReviewResponse | null>(null);
  const [error, setError] = useState<AnalysisError | null>(null);
  const [showAbout, setShowAbout] = useState(false);

  const handleAnalyze = async (input: string, mode: 'url' | 'text') => {
    setStatus(AnalysisStatus.ANALYZING);
    setError(null);
    try {
      let result;
      if (mode === 'url') {
        result = await analyzeSubstackPost(input);
      } else {
        result = await analyzeRawText(input);
      }
      setData(result);
      setStatus(AnalysisStatus.COMPLETED);
    } catch (err: any) {
      console.error(err);
      setError({ message: err.message || "An unexpected error occurred." });
      setStatus(AnalysisStatus.ERROR);
    }
  };

  const handleReset = () => {
    setStatus(AnalysisStatus.IDLE);
    setData(null);
    setError(null);
  };

  return (
    <div className="min-h-screen bg-[#131313] pb-12 text-gray-100">
      <AboutModal isOpen={showAbout} onClose={() => setShowAbout(false)} />
      
      {/* Navbar */}
      <nav className="bg-[#1c1c1c] border-b border-[#333] sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex items-center">
              <div className="bg-[#ff5722] p-1.5 rounded-lg mr-3">
                <BookOpen className="h-6 w-6 text-white" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-white tracking-tight">Substack Critic</h1>
                <p className="text-xs text-gray-400 font-medium hidden sm:block">Fact-Check & Balance</p>
              </div>
            </div>
            <div className="flex items-center space-x-4">
              <button 
                onClick={() => setShowAbout(true)}
                className="text-sm font-medium text-gray-400 hover:text-white transition-colors focus:outline-none"
              >
                About
              </button>
              <span className="h-4 w-px bg-[#333]"></span>
              <div className="text-xs text-gray-500 bg-[#262626] px-2 py-1 rounded border border-[#333]">
                Powered by Gemini 2.5
              </div>
            </div>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-8 md:pt-12">
        
        {/* Intro Text (Only show when idle) */}
        {status === AnalysisStatus.IDLE && (
          <div className="text-center mb-10 max-w-2xl mx-auto">
            <h2 className="text-3xl font-bold text-white mb-4">
              Bring Balance to the Conversation
            </h2>
            <p className="text-lg text-gray-400">
              Paste a Substack URL or the full article text below. We'll identify the main claims, check them against major news outlets, and generate a constructive, fact-based counter-point.
            </p>
          </div>
        )}

        {/* Error Display */}
        {status === AnalysisStatus.ERROR && error && (
          <div className="mb-8 bg-red-900/20 border border-red-900/30 rounded-lg p-4 flex items-start">
            <AlertCircle className="w-5 h-5 text-red-500 mt-0.5 mr-3 flex-shrink-0" />
            <div>
              <h3 className="text-sm font-medium text-red-400">Analysis Failed</h3>
              <p className="text-sm text-red-400/80 mt-1">{error.message}</p>
              <button 
                onClick={() => setStatus(AnalysisStatus.IDLE)}
                className="mt-3 text-sm font-medium text-red-400 hover:text-red-300 underline"
              >
                Try Again
              </button>
            </div>
          </div>
        )}

        {/* Dynamic Components */}
        <div className="transition-all duration-300">
          {status === AnalysisStatus.IDLE || status === AnalysisStatus.ANALYZING || status === AnalysisStatus.ERROR ? (
            <InputSection 
              onAnalyze={handleAnalyze} 
              isAnalyzing={status === AnalysisStatus.ANALYZING} 
            />
          ) : (
            data && <ReviewDisplay data={data} onReset={handleReset} />
          )}
        </div>
        
      </main>

      <footer className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 mt-16 border-t border-[#333] pt-8">
        <p className="text-center text-sm text-gray-600">
          &copy; {new Date().getFullYear()} Substack Critic. All analysis generated by AI and verified via Google Search.
        </p>
      </footer>
    </div>
  );
};

export default App;
