import React from 'react';
import { X, Info, ShieldAlert } from 'lucide-react';

interface AboutModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const AboutModal: React.FC<AboutModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6">
      <div 
        className="absolute inset-0 bg-black/80 backdrop-blur-sm transition-opacity" 
        onClick={onClose}
      />
      <div className="relative w-full max-w-lg bg-[#1c1c1c] border border-[#333] rounded-xl shadow-2xl p-6 md:p-8 animate-in fade-in zoom-in-95 duration-200">
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 p-1 text-gray-500 hover:text-white transition-colors"
          aria-label="Close modal"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center space-x-3 mb-6">
          <div className="bg-blue-500/10 p-2 rounded-lg border border-blue-500/20">
            <Info className="w-6 h-6 text-blue-400" />
          </div>
          <h2 className="text-xl font-bold text-white">About Project</h2>
        </div>

        <div className="space-y-4 text-gray-300 leading-relaxed text-sm">
          <p>
            The <strong className="text-white">Substack Critic & Balancer</strong> is a research tool designed to foster critical thinking and constructive discourse. 
            It reads Substack posts, identifies the core assertions, and rigorously checks them against major news outlets and verified sources.
          </p>
          <p>
            Our goal is not to silence authors but to provide a 
            <span className="text-orange-500"> balanced counter-perspective</span> rooted in evidence, helping readers navigate complex topics with a broader view.
          </p>

          <div className="bg-yellow-900/10 border border-yellow-900/30 rounded-lg p-4 mt-6">
            <div className="flex items-start space-x-3">
              <ShieldAlert className="w-5 h-5 text-yellow-500 flex-shrink-0 mt-0.5" />
              <div>
                <h3 className="text-sm font-semibold text-yellow-500 mb-1">Disclaimer</h3>
                <p className="text-xs text-yellow-400/80">
                  The feedback provided by this application is generated by Google's Gemini AI. 
                  It does not constitute an agreement, endorsement, or assertion of fact by the developers. 
                  This tool relies on AI to collect, analyze, and present the response. 
                  Users should independently verify all information.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-8 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-[#333] hover:bg-[#404040] text-white text-sm font-medium rounded-lg transition-colors border border-gray-700"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
